"""Hoopshype salary-table collection and lossless source parsing."""

from nba_commish.hoopshype.aggregation import (
    AggregationCompletionStatus,
    AggregationReason,
    DecisionSource,
    DispositionEvidence,
    DispositionStatus,
    PlayerSalaryAggregation,
    SalaryAggregationResult,
    SalaryRowDisposition,
    SourcePlayerKey,
    aggregate_salary_rows,
)
from nba_commish.hoopshype.csv_fallback import (
    CSV_HEADER,
    CSV_HEADER_FIELDS,
    CommissionerCsvImport,
    CsvFallbackDiagnostic,
    CsvFallbackRunResult,
    ReconciliationResult,
    build_csv_fallback_artifact,
    import_commissioner_csv,
    load_csv_fallback_artifact,
    load_synthetic_csv_fixture_for_tests,
    reconcile_salary_rows,
    run_csv_fallback_import,
)
from nba_commish.hoopshype.deduplication import (
    DeduplicationResult,
    SourceRowOccurrence,
    deduplicate_salary_rows,
    fingerprint_salary_row,
)
from nba_commish.hoopshype.errors import (
    AggregationDecisionError,
    AggregationError,
    AggregationValidationError,
    CsvFallbackArtifactError,
    CsvFallbackError,
    CsvFallbackReconciliationError,
    CsvFallbackValidationError,
    FingerprintCollisionError,
    FingerprintError,
    FingerprintValidationError,
    SalaryParseError,
)
from nba_commish.hoopshype.pipeline import run_import
from nba_commish.hoopshype.salary import (
    normalize_salary_row,
    normalize_salary_rows,
    parse_salary_text,
)

__all__ = [
    "CSV_HEADER",
    "CSV_HEADER_FIELDS",
    "AggregationCompletionStatus",
    "AggregationDecisionError",
    "AggregationError",
    "AggregationReason",
    "AggregationValidationError",
    "CommissionerCsvImport",
    "CsvFallbackArtifactError",
    "CsvFallbackDiagnostic",
    "CsvFallbackError",
    "CsvFallbackReconciliationError",
    "CsvFallbackRunResult",
    "CsvFallbackValidationError",
    "DecisionSource",
    "DeduplicationResult",
    "DispositionEvidence",
    "DispositionStatus",
    "FingerprintCollisionError",
    "FingerprintError",
    "FingerprintValidationError",
    "PlayerSalaryAggregation",
    "ReconciliationResult",
    "SalaryAggregationResult",
    "SalaryParseError",
    "SalaryRowDisposition",
    "SourcePlayerKey",
    "SourceRowOccurrence",
    "aggregate_salary_rows",
    "build_csv_fallback_artifact",
    "deduplicate_salary_rows",
    "fingerprint_salary_row",
    "import_commissioner_csv",
    "load_csv_fallback_artifact",
    "load_synthetic_csv_fixture_for_tests",
    "normalize_salary_row",
    "normalize_salary_rows",
    "parse_salary_text",
    "reconcile_salary_rows",
    "run_csv_fallback_import",
    "run_import",
]
